[general]
import = [
    # "~/.config/alacritty/themes/themes/aura.toml"
    # "~/.cache/wal/colors-alacritty.toml",
    "colors.toml"
]

[font]
normal = {family = "GeistMono Nerd Font", style = "Regular" }
bold = { family = "GeistMono Nerd Font", style = "Bold" }
italic = { family = "GeistMono Nerd Font", style = "Italic" }
bold_italic = { family = "GeistMono Nerd Font", style = "Bold Italic" }
size = 13  # Adjust size as needed

[window]
padding = { x = 10, y = 10 }  # Adjust padding as needed
opacity = 1
decorations = "full"

[colors.primary]
background = "#000000"
foreground = "#FFFFFF"

[colors]
draw_bold_text_with_bright_colors = true
transparent_background_colors = false

[selection]
save_to_clipboard = true
