[colors.primary]
background = '#111318'
foreground = '#e1e2e9'
 
[colors.cursor]
text = '#e1e2e9'
cursor = '#c3c6cf' 
 
[colors.vi_mode_cursor]
text = '#111318'
cursor = '#a4c9fe' 
 
[colors.search.matches]
foreground = '#43474e' 
background = '#d9bde3' 
 
[colors.search.focused_match]
foreground = '#43474e' 
background = '#a4c9fe' 
 
[colors.footer_bar]
foreground = '#43474e' 
background = '#e1e2e9' 
 
[colors.hints.start]
foreground = '#43474e' 
background = '#bcc7db' 
 
[colors.hints.end]
foreground = '#43474e' 
background = '#bcc7db' 
 
[colors.selection]
text = '#111318'
background = '#a4c9fe'
 
 
[colors.normal]
black = '#181818' 
red = '#ffb4ab' 
green = '#a4c9fe' 
yellow = '#3a608f' 
blue = '#a4c9fe' 
magenta = '#d9bde3' 
cyan = '#bcc7db' 
white = '#BAC2DE' 
 
 
[colors.bright]
black = '#585B70' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#A6ADC8' 
 
 
[colors.dim]
black = '#45475A' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#BAC2DE' 
