add_newline = false
format = """[$custom](dimmed white) $username:$directory $git_branch$git_status| """

palette = "nord"

[palettes.nord]
color1 = "{{colors.primary_fixed_dim.default.hex}}"
color2 = "{{colors.on_primary.default.hex}}"
color3 = "{{colors.on_surface_variant.default.hex}}"
color4 = "{{colors.surface_container.default.hex}}"
color5 = "{{colors.on_primary.default.hex}}"
color6 = "{{colors.surface_dim.default.hex}}"
color7 = "{{colors.surface.default.hex}}"
color8 = "{{colors.primary.default.hex}}"
color9 = "{{colors.tertiary.default.hex}}"

[custom.time]
command = 'date +"[%H:%M]"'
when = "true"
format = "[$output]($style)"
style = "dimmed white"

[username]
show_always = true
format = "[$user]($style)"
# style_user = "#b8c2bb"
style_user = "color3"

[directory]
format = "[$path]($style)"
style = "bold color1" 
truncation_length = 1
truncate_to_repo = false

[git_branch]
format = '[\($branch\)]($style)'
# style = "#8abeb7"
style = "color9"


[git_status]
format = "[$all_status]($style) "
style = "color9"
