add_newline = false
format = """[$custom](dimmed white) $username:$directory $git_branch$git_status| """

palette = "nord"

[palettes.nord]
color1 = "#82d5c8"
color2 = "#003731"
color3 = "#bec9c6"
color4 = "#1a2120"
color5 = "#003731"
color6 = "#0e1513"
color7 = "#0e1513"
color8 = "#82d5c8"
color9 = "#adcae6"

[custom.time]
command = 'date +"[%H:%M]"'
when = "true"
format = "[$output]($style)"
style = "dimmed white"

[username]
show_always = true
format = "[$user]($style)"
# style_user = "#b8c2bb"
style_user = "color3"

[directory]
format = "[$path]($style)"
style = "bold color1" 
truncation_length = 1
truncate_to_repo = false

[git_branch]
format = '[\($branch\)]($style)'
# style = "#8abeb7"
style = "color9"


[git_status]
format = "[$all_status]($style) "
style = "color9"
