add_newline = false
format = """[$custom](dimmed white) $username:$directory $git_branch$git_status| """

palette = "nord"

[palettes.nord]
color1 = "#b6c4ff"
color2 = "#1d2d61"
color3 = "#c6c6d0"
color4 = "#1e1f25"
color5 = "#1d2d61"
color6 = "#121318"
color7 = "#121318"
color8 = "#b6c4ff"
color9 = "#e3bada"

[custom.time]
command = 'date +"[%H:%M]"'
when = "true"
format = "[$output]($style)"
style = "dimmed white"

[username]
show_always = true
format = "[$user]($style)"
# style_user = "#b8c2bb"
style_user = "color3"

[directory]
format = "[$path]($style)"
style = "bold color1" 
truncation_length = 1
truncate_to_repo = false

[git_branch]
format = '[\($branch\)]($style)'
# style = "#8abeb7"
style = "color9"


[git_status]
format = "[$all_status]($style) "
style = "color9"
